export const SYNC_TABLES = [
  "abyss_items",
  "projects",
  "project_templates",
  "phases",
  "protected_block_templates",
  "protected_blocks",
  "week_day_priorities",
  "bingo_cards",
  "goals",
  "goal_milestones",
  "quarter_themes",
  "month_intentions",
  "reserved_days",
  "planning_suggestions",
  "tasks",
  "task_time_entries",
  "task_dependencies",
  "task_recurrence",
  "task_occurrence_overrides",
  "chat_messages",
  "daily_wins",
  "evidence_editions",
  "day_reviews",
  "app_settings",
  "category_settings",
  "nudge_events",
  "task_bulk_imports",
  "task_bulk_import_items",
  "care_activities",
  "care_events",
  "care_reflections",
  "user_values",
  "about_me_sections",
  "user_constraints",
  "about_me_suggestions",
] as const;

export type SyncTable = (typeof SYNC_TABLES)[number];

export type SyncOp = "insert" | "update" | "delete";
